name: Build QuickJs

on: 
  workflow_dispatch:

jobs:

  ##################################
  #       for linux system
  ##################################
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Deps
      run: sudo apt-get install texlive

    - name: Build QuickJs
      run: |
        make -e all -j4
        make -e build_doc

    - name: Cache Binaries
      uses: actions/upload-artifact@v2
      with:
        name: quickjs-linux
        path: |
          quickjs.h
          quickjs-libc.h
          doc
          *.a
          *.so
          qjs*
          run-*
        retention-days: 5
  
  ################################
  #      for win32 system
  ################################
  build_win32:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install MinGW
      # You may pin to the exact commit or the version.
      # uses: egor-tensin/setup-mingw@f3c5d799aadf8fa230ac67a422b01dd085bbc96b
      uses: egor-tensin/setup-mingw@v2
      with:
        # Target platform
        platform: x64
        # Install Cygwin packages
        cygwin: 0 # optional, default is 0
        # Enable static linking workaround
        static: 1 # optional, default is 1
        # Set up cc/c++ executables
        cc: 1 # optional, default is 1
        # On Cygwin, replace executable symlinks with hardlinks
        hardlinks: 0 # optional, default is 0

    - name: Install Deps
      run: sudo apt-get install texlive

    - name: Build QuickJs
      run: |
        make -e CONFIG_WIN32=y all -j4
        make -e CONFIG_WIN32=y build_doc

    - name: Cache Binaries
      uses: actions/upload-artifact@v2
      with:
        name: quickjs-win32
        path: |
          quickjs.h
          quickjs-libc.h
          doc
          *.a
          *.so
          *.exe
        retention-days: 5
        
