name: test-CI

on: [push]

jobs:
  windows-msvc:
    runs-on: windows-latest
    steps:
      - name: Setup Windows 10 SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: 20348
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: install just
        shell: powershell
        run: |
          winget install --id Casey.Just --exact --disable-interactivity --accept-source-agreements
          winget install xmake --disable-interactivity --accept-source-agreements
      - uses: actions/checkout@v3
      - name: 
        shell: powershell
        run: |
          $env:path+=";C:\Users\$($env:username)\AppData\Local\Microsoft\WinGet\Links"
          just test

  windows-mingw:
    runs-on: windows-latest
    steps:
      - name: Install dependency
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            git
            p7zip
      - uses: actions/checkout@v3
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: install just
        shell: powershell
        run: |
          winget install --id Casey.Just --exact --disable-interactivity --accept-source-agreements
          winget install --id Xmake-io.Xmake --disable-interactivity --accept-source-agreements
      - name: build
        shell: msys2 {0}
        run: |
          export PATH="${PATH}:~/AppData/Local/Microsoft/WinGet/Links"
          just test
  osx:
    name: macos build
    runs-on: macos-latest
    steps:
      - name: install-xmake
        run: |
          brew install xmake just
          xmake --version
      - uses: actions/checkout@v3
      - name: build
        run: |
          just test
  linux:
    name: linux build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install-xmake
        run: |
          ./scripts/xmake-install.sh xmake-amd64.deb
          sudo apt-get install -y ./xmake-amd64.deb
          rm ./xmake-amd64.deb
          xmake --version
      - name: install just
        uses: extractions/setup-just@v1
      - name: build
        run: |
          just test
