on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Clang
        if: matrix.os == 'ubuntu-latest'
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Setup Cmake
        uses: lukka/get-cmake@latest

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Tests in Debug mode
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ci"
          buildPreset: "run-tests"

      - name: Run Tests in Release mode
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ci"
          buildPreset: "run-tests"
          buildPresetAdditionalArgs: '["--config Release"]'
