on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.11.1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          echo $PATH
          mkdir build && cd build 
          cmake .. --fresh -G Ninja -DCMAKE_BUILD_TYPE=Release 
          ninja tests && ctest --test-dir tests
        shell: bash
