on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Clang
        if: matrix.os == 'ubuntu-latest'
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Setup Cmake
        uses: lukka/get-cmake@latest

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 37fce29a263a1546262eaed6af7ccac53b0094cd

      - name: Run Tests in Debug mode
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ci"
          buildPreset: "ci"

      - name: Run Tests in Release mode
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ci"
          buildPreset: "ci"

      - name: Run Tests in Debug mode
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ci"
          configurePresetAdditionalArgs: '[-DCMAKE_BUILD_TYPE=Release]'
          buildPreset: "ci"

      - name: Run test build boost in debug mode
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ci:boost"
          buildPreset: "ci:boost"

      - name: Run test build boost in release mode
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ci:boost"
          configurePresetAdditionalArgs: '[-DCMAKE_BUILD_TYPE=Release]'
          buildPreset: "ci:boost"
