on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Clang
        if: matrix.os == 'ubuntu-latest'
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Setup Cmake
        uses: lukka/get-cmake@latest

      - name: Checkout code
        uses: actions/checkout@v2

      - name: debug:run-tests
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "default"
          buildPreset: "run-tests"

      - name: release:run-tests
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "default"
          configurePresetAdditionalArgs: "['-DCMAKE_BUILD_TYPE=Release']"
          buildPreset: "run-tests"

      - name: debug:test-col
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "dump-token"
          buildPreset: "test-col"

      - name: release:test-col
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "dump-token"
          configurePresetAdditionalArgs: "['-DCMAKE_BUILD_TYPE=Release']"
          buildPreset: "test-col"

      - name: debug:test-op_loc
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "dump-bytecode-2"
          buildPreset: "test-op_loc"

      - name: release:test-op_loc
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "dump-bytecode-2"
          configurePresetAdditionalArgs: "['-DCMAKE_BUILD_TYPE=Release']"
          buildPreset: "test-op_loc"
